id = "groovy-enhanced"
name = "Groovy-Enhanced"
version = "1.4.0"
schema_version = 1
authors = ["Valentine Briese <valentinegb@icloud.com>", "hdbeworks@gmail.com"]
description = "Enhanced Groovy (build.gradle) support."
repository = "https://github.com/HBDE-work/zed-groovy-enhanced"

[language_servers.groovy-enhanced]
name = "Groovy Enhanced"
language = "Groovy"

[grammars.groovy]
repository = "https://github.com/murtaza64/tree-sitter-groovy"
rev = "deb0dcf8c4544f07564060f6e9b9f6e4b0bfc27d"
